[package]
name = "rust"
version = "0.1.0"
authors = ["pauliancu97 <paul97iancu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
queues = "1.0.2"
md5 = "0.7.0"